### ISSUE TITLE
Extension fails to open up any Lyric-Views

### ISSUE THREAD

**Issue by Lunascaped** [surfbryce/beautiful-lyrics#151]
Latest Spotify
Latest Spicetify
Latest Extension Version

Here is the photo of the error:

<img width="1175" alt="Spotify_6vDsOzHq9f" src="https://github.com/surfbryce/beautiful-lyrics/assets/21148758/a0f9fb48-2207-4606-98db-f3d4bed6ce50">
<img width="928" alt="Spotify_1cloPrPkT1" src="https://github.com/surfbryce/beautiful-lyrics/assets/21148758/0bf8c9f1-8b53-41e6-b9c8-2b12d2c54240">

If anymore information is needed I can happily provide it.
I am able to click the lyrics page button and view the lyrics that way, but I cannot click Full Screen.
<img width="1899" alt="Spotify_qvfOHHGUwA" src="https://github.com/surfbryce/beautiful-lyrics/assets/21148758/49c3dec1-98a7-4760-975b-7f4143d52187">
It makes the client go blank

**Comment by surfbryce** [comment]
@Lunascaped Thank you so much for clicking on the error to view the code that was causing it. I've seen the error reported before but since the errors didn't actually link to the code that I was seeing it was hard to diagnose.

This makes it extremely easy to figure out how to solve this and what may be causing this. I really appreciate it thanks, I'll take a look at it today!

**Comment by surfbryce** [comment]
Alright @Lunascaped I've pushed out a minor update 3.1.17, it's not official yet but I've made a change that should hopefully remedy this. Let me know if it works for you or not.

**Comment by sinrn** [comment]
> Alright @Lunascaped I've pushed out a minor update 3.1.17, it's not official yet but I've made a change that should hopefully remedy this. Let me know if it works for you or not.

Hi, I'm experiencing the same error and the fix doesn't work for me. I have confirmed it updated from the notification on startup.  The behavior on my client is the same as noted here in the bug report.

**Comment by Lunascaped** [comment]
> Alright @Lunascaped I've pushed out a minor update 3.1.17, it's not official yet but I've made a change that should hopefully remedy this. Let me know if it works for you or not.

I went ahead and tested it but it still seems to be broken with the same error, yes I added it directly from the distribution file and not the marketplace so the update was installed correctly. If it helps at all, I am using a 4k Monitor at 3840 x 2160
I remember it working on my laptop which has a 1920 x 1080 screen.
<img width="741" alt="Spotify_0WBkm7wPyQ" src="https://github.com/surfbryce/beautiful-lyrics/assets/21148758/337bbd30-0308-45ab-b4a5-90b52ac99c27">
<img width="1173" alt="Spotify_ZwXyoxk3yI" src="https://github.com/surfbryce/beautiful-lyrics/assets/21148758/c48be93c-c90f-49ab-801e-ad2346e0a1d0">

**Comment by IdkWhatToCallMe123** [comment]
I have the same issue but only on my Linux machine tho

**Comment by Lunascaped** [comment]
Still encountering this issue
<img width="439" alt="Spotify_PXIH2AP8gb" src="https://github.com/surfbryce/beautiful-lyrics/assets/21148758/116c1771-2bfc-4cfc-86fe-0fe702cdf3b7">

**Comment by sslusshi** [comment]
Hi, I just downloaded the extension and I have the same issue. It won't even let me go into full screen mode at all. Did all the recommended things to do in the experimental features settings, but nothing fixed.
